version: '3'
services:

  backend:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      -  mongo
    volumes:
      -  type: bind
         source: ${DATASET_PATH}
         target: /mnt/dataset/

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE='MDEP'
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - '${MONGODB_VOLUME}:/data/db'