version: '2'
services:

  backend:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      -  mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: 'MDEP'