version: '3'
services:

  backend:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      -  mongo
    volumes:
      -  type: bind
         source: /mnt/dataset/
         target: /mnt/dataset/

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: 'MDEP'